/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MapRouteImport } from './routes/map'
import { Route as PostureRouteImport } from './routes/posture'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ThresholdsRouteImport } from './routes/thresholds'
import { Route as TimelineRouteImport } from './routes/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PostureRoute = PostureRouteImport.update({
  id: '/posture',
  path: '/posture',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ThresholdsRoute = ThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRoute
  '/copilot': typeof CopilotRoute
  '/deployment': typeof DeploymentRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/posture': typeof PostureRoute
  '/risk': typeof RiskRoute
  '/thresholds': typeof ThresholdsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRoute
  '/copilot': typeof CopilotRoute
  '/deployment': typeof DeploymentRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/posture': typeof PostureRoute
  '/risk': typeof RiskRoute
  '/thresholds': typeof ThresholdsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRoute
  '/copilot': typeof CopilotRoute
  '/deployment': typeof DeploymentRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/posture': typeof PostureRoute
  '/risk': typeof RiskRoute
  '/thresholds': typeof ThresholdsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assets'
    | '/copilot'
    | '/deployment'
    | '/events'
    | '/map'
    | '/posture'
    | '/risk'
    | '/thresholds'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assets'
    | '/copilot'
    | '/deployment'
    | '/events'
    | '/map'
    | '/posture'
    | '/risk'
    | '/thresholds'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/assets'
    | '/copilot'
    | '/deployment'
    | '/events'
    | '/map'
    | '/posture'
    | '/risk'
    | '/thresholds'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AssetsRoute: typeof AssetsRoute
  CopilotRoute: typeof CopilotRoute
  DeploymentRoute: typeof DeploymentRoute
  EventsRoute: typeof EventsRoute
  MapRoute: typeof MapRoute
  PostureRoute: typeof PostureRoute
  RiskRoute: typeof RiskRoute
  ThresholdsRoute: typeof ThresholdsRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posture': {
      id: '/posture'
      path: '/posture'
      fullPath: '/posture'
      preLoaderRoute: typeof PostureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thresholds': {
      id: '/thresholds'
      path: '/thresholds'
      fullPath: '/thresholds'
      preLoaderRoute: typeof ThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AssetsRoute: AssetsRoute,
  CopilotRoute: CopilotRoute,
  DeploymentRoute: DeploymentRoute,
  EventsRoute: EventsRoute,
  MapRoute: MapRoute,
  PostureRoute: PostureRoute,
  RiskRoute: RiskRoute,
  ThresholdsRoute: ThresholdsRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
